import { getPosts } from '@/apis/postAPI';
import Link from 'next/link';
import React from 'react';
import { Headland_One } from 'next/font/google';
// import { redirect } from 'next/dist/server/api-utils';

const headland = Headland_One({ weight: ['400'], subsets: ['latin'] });

export const metadata = {
    title: "Posts",
    description: "Generated by create next app",
    keywords: ['about', 'post', 'home']
};

// const getPosts = async () => {
//     const res = await fetch('https://jsonplaceholder.typicode.com/posts');
//     const data = await res.json();
//     if (data) {
//         redirect(`/posts/${data[0].id}`);
//     }
//     return data;
// }

const page = async () => {
    const postData = await getPosts();
    return (
        <div className={`${headland.className}`}>
            <h6 className='text-center text-2xl font-bold my-4 text-blue-950'>All Posts</h6>
            <div className='grid grid-cols-4 gap-8 p-8'>
                {
                    postData?.slice(0, 20)?.map(({ id, title, body }) =>
                        <div key={id} className='border-2 p-4'>
                            <h6>{title}</h6>
                            <h6>{body}</h6>
                            <button className='btn'><Link href={`/posts/${id}`}>View Details</Link></button>
                        </div>
                    )
                }
            </div>
        </div>
    );
};

export default page;